name: BuildMaster

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - name: Start Build & Test
      run: echo 'Started at ${{ steps.start.outputs.time }}.'
      id: start
    - name: Checkout
      uses: actions/checkout@v2
      id: co
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
      id: setup
    - name: Install dependencies
      run: dotnet restore
      id: restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
      id: build
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      id: test
    - name: Finish build & Test
      run: echo 'Finished at ${{ steps.finish.outputs.time }}.'
      id: finish
  release:
    name: Release
    if: ${{ github.ref == 'master' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Start Package & Publish
      run: echo 'Started at ${{ steps.start.outputs.time }}.'
      id: start
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Package Release
      run: dotnet pack --configuration Release -o out
    - name: Publish to NuGet
      run: dotnet nuget push out/ReadOnlySet.1.0.0.nupkg -k ${{secrets.NUGET_API_KEY_DEFAULT}} -s https://api.nuget.org/v3/index.json
      id: PublishToNuGet
    - name: Finish Package & Publish
      run: echo 'Finished at ${{ steps.finish.outputs.time }}.'
      id: finish
